### PR TITLE
Add a plotting function for 1D dependency

### LINKED ISSUE #118: Separate 1D and 2D parts of plot_objective
The output figure from plot_objective is a bit of a monster that tries to convey many different types of information at once. Especially the mixing of 1D and 2D plotting takes new users a rather long time to deconvolute.

I think it would be good to create two new functions, with names like plot_objective_1d and plot_objective_2d, that separates the two types of plot. This will give us more freedom to make design changes to how each kind of information is communicated to the end user. We can keep plot_objective around for backwards compatibility.

The 2D plot_objective will be essentially unchanged, while I imagine the 1D version will look something like the mock-up shown below. Input on whether to force inclusion of explanatory text in the figure is very welcome.
1D_plot_objective_mockup

### PR DESCRIPTION
**Pull request by dk-teknologisk-mon**
I've built a function that creates a plot of the 1D dependency (the diagonal only from the plot_objective plot) in a figure of its own.  As part of this addition I have also created two simple integration tests for plot_objective and plot_objective_1d that basically just check that nothing breaks when building the figures.

Some example outputs for 1, 2, 4, 5 and 10 factors, all built using real data:
Dependency_1D_1_factor
Dependency_1D_2_factors
Dependency_1D_4_factors
Dependency_1D_5_factors
Dependency_1D_10_factors

### CODE REVIEW

**Comment by dk-teknologisk-mon** [comment]
So in the testing with bleeding edge dependencies, we're getting errors in something related to the bokeh-package - which I haven't touched at all in any of my edits... From the debugging message that it's throwing it also looks like the problem originates in an internal method in the package itself, or am I reading that wrong? How to proceed from here?

**Comment by SRFU-NN** [comment]
A new version of bokeh was released this Monday. Try and force it to use the old version, and see if the pipeline works.

Sendt fra min iPhone

Den 2. nov. 2022 kl. 03.38 skrev Morten Bormann Nielsen ***@***.***>:

﻿

Caution: This email originated from outside of the Novo Nordisk email system. Use caution when clicking on links or opening attachments.


So in the testing, we're getting errors in something related to the bokeh-package - which I haven't touched at all in any of my edits... From the debugging message that it's throwing it also looks like the problem originates in an internal method in the package itself, or am I reading that wrong? How to proceed from here?

**Comment by sqbl** [comment]
Updates have been made in develop to counter the problem with bokeh plot. In short, bokeh updated and broke stuff

**Review by sqbl — APPROVED** [review]
LGTM,
This is a nice addition to the package. Well done.
After upgrading to 0.7.6 we pulled the new updated develop branch into this branch/PR. Hopefully everything plays nice, when we hit “merge”…

**Pull request merged**
