### PR TITLE
Adds documentation for how sum constraints work

### PR DESCRIPTION
**Pull request by dk-teknologisk-mon**
This Jupyter notebook demonstrates the use of sum constraints (A + B = 42), and illustrates where initial sampling points are located in a constrained space. The notebook will be expanded over time to include examples of new samples drawn based on a model and an acquisition function.

### CODE REVIEW

**Comment by SRFU-NN** [comment]
```
# This model system is designed to operate on the space:
# [(-3.0, 3.0), (-3.0, 3.0), (-2.0, 2.0), (0, 2)]
...
dimensions = [(0.0, 10.0), (0.0, 10.0), (0.0, 10.0), (0, 2)]
```

Shouldn't these coincide?

**Comment by SRFU-NN** [comment]
You never actually use the score, do you? Shouldn't we wait with having it (and then hopefully have a new noise model class to implement it with)?

**Comment by SRFU-NN** [comment]
The rest is nice 👍

**Review by SRFU-NN — COMMENTED** [review]
See comments in conversation.

**Comment by dk-teknologisk-mon** [comment]
I figured out how to add this notebook via the larger pull request that implements SumEquals constraints, so it makes no sense to have this as its own pull request.

**Pull request closed without merging**
