### PR TITLE
Works with sklearn 1.2.0

### LINKED ISSUE #136: Adjusting to new sklearn version
"mse" has changed name to "friedman_mse" in sklearn 1.2.0 (we think).

There is also a floating point error which needs fixing in bleeding edge tests. Probably np.allclose will do.

### PR DESCRIPTION
**Pull request by SRFU-NN**
fix: replaced mse with friedman_mse

### CODE REVIEW

**Comment by SRFU-NN** [comment]
I have also replaced one assert_array_equal with assert_array_almost_equal, as that specific comparison gave floating point errors, probably do to exp(log(x)).

We should consider whether to replace all assert_array_equal with assert_array_almost_equal to avoid such errors in the future, in most cases they don't matter, and are just annoying to fix.

**Comment by SRFU-NN** [comment]
We are specifically mentioning one other option for tree criteria, should we mention all that are possible in sklearn?

**Comment by SRFU-NN** [comment]
Should we mention that "Training using “absolute_error” is significantly slower than when using “squared_error”."?

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html

**Review by sqbl — APPROVED** [review]
LGTM

**Pull request merged**
