### PR TITLE
Matrix to ndarray

### PR DESCRIPTION
**Pull request by sqbl**
In order to fix a deprecation warning: the use of scipy.matrix is replaced with using np.ndarrays. 
It required a bit more custom coding and addition of helper functions than I had originally expected

### CODE REVIEW

**Comment by SRFU-NN** [comment]
SciPy has a null space function which seems to work on numpy arrays, any reason why we aren't using that?

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.null_space.html

Edit: We would, of course, have to pin the version of scipy to "newer than 6 years old" if we are to use that.

**Comment by sqbl** [comment]
When I tried the scipy version (which would be a much cleaner approach, yes), it failed our tests. I'm not looking more into it right now (surely it can be solved).

**Comment by SRFU-NN** [comment]
In that case it seems good. My only comment is that we are assuming that numpy.linalg.svd returns the eigenvalues in descending order (we find the number of non-zero ones and take that many from the start of the list of eigenvectors), but since it says that it does so in the documentation, it shouldn't be a problem.

**Comment by SRFU-NN** [comment]
@sqbl This has now become urgent. The newest version of scipy does not include scipy.matrix, making our pipelines fail. We can't finish any other pull requests until this has been done.

**Review by SRFU-NN — APPROVED** [review]
LGTM

**Comment by sqbl** [comment]
I would be ok with you merging this. If anything, we should let Morten have a say. Afterall, it is his original code that I butcher with my quick-fix.

**Pull request merged**
